---
- hosts: localhost
  connection: local 
  become: true
  tasks:
  - name: Install htop
    apt: name=htop
  - name: Install docker
    apt: name=docker
  - name: Install jq
    apt: name=jq
  - name: Install tmux
    apt: name=tmux
  - name: Install tree
    apt: name=tree
  - name: Install gparted
    apt: name=gparted
  - name: Install git
    apt: name=git
  - name: Install pavucontrol
    apt: name=pavucontrol
  - name: Install python3-pip
    apt: name=python3-pip
  - name: Install vim
    apt: name=vim

